config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'cars#index'
  resources :cars
  resources :customers
  resources :rental_orders

end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id            :integer          not null, primary key
#  make          :string
#  model         :string
#  description   :text
#  comfort_class :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Car < ActiveRecord::Base
  has_many :rental_orders
  has_many :customers, through: :rental_orders

  validates :make, :model, :comfort_class, presence: true
  validates :comfort_class, inclusion: {in: %w(A B C),
    message: "%{value} is not a valid car comfort class" }

  def booked_dates
    booked_dates = []
    self.rental_orders.each do |rental_order|
      (rental_order.start_date.to_i..rental_order.end_date.to_i).step(1.day) do |date|
        booked_dates << date
      end
    end
    booked_dates
  end
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string
#  surname    :string
#  address    :string
#  city       :string
#  zip_code   :string
#  notes      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ActiveRecord::Base
  has_many :rental_orders
  has_many :cars, through: :rental_orders

  validates :name, :surname, :address, :city, :zip_code, presence: true
end

app/models/rental_order.rb
# == Schema Information
#
# Table name: rental_orders
#
#  id          :integer          not null, primary key
#  customer_id :integer
#  user_id     :integer
#  car_id      :integer
#  start_date  :datetime
#  end_date    :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class RentalOrder < ActiveRecord::Base
  belongs_to :customer
  belongs_to :user
  belongs_to :car

  validates :customer_id, :user_id, :car_id, :start_date, :end_date, presence: true
  validate :start_date_cannot_be_in_the_past, on: :create
  validate :end_date_cannot_be_in_the_past
  validate :date_cannot_be_already_booked
  validate :end_date_must_be_after_start_date


  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end

  def end_date_cannot_be_in_the_past
    if end_date.present? && end_date < Date.today
      errors.add(:end_date, "can't be in the past")
    end
  end

  def end_date_must_be_after_start_date
    if end_date.present? && start_date.present? && end_date < start_date
      errors.add(:end_date, "can't be before start date")
    end
  end

  def date_cannot_be_already_booked
    if car_id.present?
      Car.find_by_id(car_id).rental_orders.each do |rental_order|
        if start_date.present? && start_date.between?(rental_order.start_date,rental_order.end_date)
          errors.add(:start_date, "already booked")
        end
        if end_date.present? && end_date.between?(rental_order.start_date,rental_order.end_date)
          errors.add(:start_date, "already booked")
        end
       end
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rental_orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  expose(:cars)
  expose(:car)
  protect_from_forgery with: :exception
  before_action do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end
end

app/controllers/cars_controller.rb
# == Schema Information
#
# Table name: cars
#
#  id            :integer          not null, primary key
#  make          :string
#  model         :string
#  description   :text
#  comfort_class :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class CarsController < ApplicationController
  before_action :pass_disabled_dates, only: :show
  def show

  end

  def create
    self.car = Car.new(car_params)
    if car.save
      redirect_to root_url
    else
      render :new
    end
  end

  def update
    if self.car.update(car_params)
      redirect_to root_url
    else
      render :edit
    end
  end

  private

  def car_params
    params.require(:car).permit(:make, :model, :description, :comfort_class)
  end
  def pass_disabled_dates
    gon.dates = car.booked_dates
  end
end

app/controllers/customers_controller.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string
#  surname    :string
#  address    :string
#  city       :string
#  zip_code   :string
#  notes      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CustomersController < ApplicationController
  expose(:customer)
  expose(:customers)
  def create
    self.customer = Customer.new(customer_params)
    if customer.save
      redirect_to customers_url, notice: 'Customer was successfully created.'
    else
      render :new
    end
  end

  def update
    if self.customer.update(customer_params)
      redirect_to root_url
    else
      render :edit
    end
  end


  private

  def customer_params
    params.require(:customer).permit(:name,:surname,:address,:city,:zip_code,:notes)
  end
end

app/controllers/rental_orders_controller.rb
# == Schema Information
#
# Table name: rental_orders
#
#  id          :integer          not null, primary key
#  customer_id :integer
#  user_id     :integer
#  car_id      :integer
#  start_date  :datetime
#  end_date    :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class RentalOrdersController < ApplicationController
  expose(:rental_order)
  expose(:rental_orders)
  def create
    self.rental_order = RentalOrder.new(rental_order_params)
    self.rental_order.user = current_user
    if rental_order.save
      redirect_to rental_orders_url
    else
      flash[:notice]=(rental_order.errors.full_messages)
      render :new
    end
  end

  def update
    if self.rental_order.update(rental_order_params)
      redirect_to rental_orders_url
    else
      render :edit
    end
  end

  def destroy
    if rental_order.destroy
      redirect_to rental_orders_url
    end
  end

  private

  def rental_order_params
    params.require(:rental_order).permit(:customer_id,:car_id,:start_date,:end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
# == Schema Information
#
# Table name: cars
#
#  id            :integer          not null, primary key
#  make          :string
#  model         :string
#  description   :text
#  comfort_class :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

module CarsHelper
end

app/helpers/customers_helper.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string
#  surname    :string
#  address    :string
#  city       :string
#  zip_code   :string
#  notes      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module CustomersHelper
end

app/helpers/rental_orders_helper.rb
# == Schema Information
#
# Table name: rental_orders
#
#  id          :integer          not null, primary key
#  customer_id :integer
#  user_id     :integer
#  car_id      :integer
#  start_date  :datetime
#  end_date    :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module RentalOrdersHelper
end

app/views/cars/_form.html.haml
= simple_form_for car, :html => { :class => 'form-horizontal' } do |f|
  = f.input :make
  = f.error_span :make
  = f.input :model
  = f.error_span :model
  = f.input :description
  = f.error_span :description
  = f.input :comfort_class
  = f.error_span :comfort_class
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), cars_path, :class => 'btn btn-default'

app/views/cars/edit.html.haml
- model_class = Car
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/cars/index.html.haml
- model_class = Car
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:make)
      %th= model_class.human_attribute_name(:model)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:comfort_class)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - cars.each do |car|
      %tr
        %td= link_to car.id, car_path(car)
        %td= car.make
        %td= car.model
        %td= car.description
        %td= car.comfort_class
        %td= car.created_at.strftime('%c')
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_car_path(car), :class => 'btn btn-default btn-xs'


= link_to t('.new', :default => t("helpers.links.new")), new_car_path, :class => 'btn btn-primary'

app/views/cars/new.html.haml
- model_class = Car
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/cars/show.html.haml
- model_class = Car
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize
.col-md-4
  %p
    %strong= model_class.human_attribute_name(:make) + ':'
    %br
    = car.make
  %p
    %strong= model_class.human_attribute_name(:model) + ':'
    %br
    = car.model
  %p
    %strong= model_class.human_attribute_name(:description) + ':'
    %br
    = car.description
  %p
    %strong= model_class.human_attribute_name(:comfort_class) + ':'
    %br
    = car.comfort_class


  = link_to t('.back', :default => t("helpers.links.back")), cars_path, :class => 'btn btn-default'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_car_path(car), :class => 'btn btn-default'
.row
  #my_own_legend.col-md-2
  %p.col-md-2
    Booked dates
  .row
    %div{:style => "overflow:hidden;"}
      .form-group
        .row
          .col-md-8
            #datetimepicker12
%h2 Car's Rental Orders
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:customer_id)
      %th= model_class.human_attribute_name(:car_id)
      %th= model_class.human_attribute_name(:start_date)
      %th= model_class.human_attribute_name(:end_date)
      %th= model_class.human_attribute_name(:created_at)
      %th= model_class.human_attribute_name(:cost)
  %tbody
    - car.rental_orders.each do |rental_order|
      %tr
        %td= link_to rental_order.id, rental_order_path(rental_order)
        %td= rental_order.customer.decorate.full_name
        %td= rental_order.car.decorate.full_name
        %td= rental_order.start_date.strftime('%D')
        %td= rental_order.end_date.strftime('%D')
        %td= rental_order.created_at.strftime('%c')
        %td= "#{rental_order.decorate.rental_cost} zl"
%button#refresh_button{:type => "button"} Refresh calendar for the current car

app/views/customers/_form.html.haml
= simple_form_for customer, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.error_span :name
  = f.input :surname
  = f.error_span :surname
  = f.input :address
  = f.error_span :address
  = f.input :city
  = f.error_span :city
  = f.input :zip_code
  = f.error_span :zip_code
  = f.input :notes
  = f.error_span :notes
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), customers_path, :class => 'btn btn-default'

app/views/customers/edit.html.haml
- model_class = Customer
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/customers/index.html.haml
- model_class = Customer
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:surname)
      %th= model_class.human_attribute_name(:address)
      %th= model_class.human_attribute_name(:city)
      %th= model_class.human_attribute_name(:zip_code)
      %th= model_class.human_attribute_name(:notes)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - customers.each do |customer|
      %tr
        %td= link_to customer.id, customer_path(customer)
        %td= customer.name
        %td= customer.surname
        %td= customer.address
        %td= customer.city
        %td= customer.zip_code
        %td= customer.notes
        %td= customer.created_at.strftime('%c')
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_customer_path(customer), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), customer_path(customer), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_customer_path, :class => 'btn btn-primary'

app/views/customers/new.html.haml
- model_class = Customer
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/customers/show.html.haml
- model_class = Customer
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = customer.name
%p
  %strong= model_class.human_attribute_name(:surname) + ':'
  %br
  = customer.surname
%p
  %strong= model_class.human_attribute_name(:address) + ':'
  %br
  = customer.address
%p
  %strong= model_class.human_attribute_name(:city) + ':'
  %br
  = customer.city
%p
  %strong= model_class.human_attribute_name(:zip_code) + ':'
  %br
  = customer.zip_code
%p
  %strong= model_class.human_attribute_name(:notes) + ':'
  %br
  = customer.notes


= link_to t('.back', :default => t("helpers.links.back")), customers_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_customer_path(customer), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), customer_path(customer), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "CarRental"
    = include_gon(:init => true)
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") CarRental
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Cars", cars_path
            %li= link_to "Customers", customers_path
            %li= link_to "Rental Orders", rental_orders_path
            %li= link_to "New Rental Order", new_rental_order_path

          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li
                = link_to "Log out", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Sign in", new_user_session_path
              %li
                = link_to "Sign up", new_user_registration_path

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            %h3 Our cars
            %ul.nav.nav-list
              %li.nav-header Choose one from our awesome cars
              - cars.each do |car|
                %li= link_to "#{car.make} #{car.model}", car_path(car)
                / %li= link_to "Link 2", "/path2"
                / %li= link_to "Link 3", "/path3"
      %footer
        %p &copy; Car Renting 2016

app/views/rental_orders/_form.html.haml
= simple_form_for rental_order, :html => { :class => 'form-horizontal' } do |f|
  = f.association :customer, :include_blank => false,
                  label_method: lambda { |customer| "#{customer.name} #{customer.surname}" }
  = f.error_span :customer_id
  = f.association :car, :include_blank => false,
                  label_method: lambda { |car| "#{car.make} #{car.model}" }
  = f.error_span :car_id
  = f.input :start_date
  = f.error_span :start_date
  = f.input :end_date
  = f.error_span :end_date
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), rental_orders_path, :class => 'btn btn-default'

app/views/rental_orders/edit.html.haml
- model_class = RentalOrder
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/rental_orders/index.html.haml
- model_class = RentalOrder
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:customer_id)
      %th= model_class.human_attribute_name(:car_id)
      %th= model_class.human_attribute_name(:start_date)
      %th= model_class.human_attribute_name(:end_date)
      %th= model_class.human_attribute_name(:created_at)
      %th= model_class.human_attribute_name(:cost)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - rental_orders.each do |rental_order|
      %tr
        %td= link_to rental_order.id, rental_order_path(rental_order)
        %td= rental_order.customer.decorate.full_name
        %td= rental_order.car.decorate.full_name
        %td= rental_order.start_date.strftime('%D')
        %td= rental_order.end_date.strftime('%D')
        %td= rental_order.created_at.strftime('%c')
        %td= "#{rental_order.decorate.rental_cost} zl"
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_rental_order_path(rental_order), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), rental_order_path(rental_order), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_rental_order_path, :class => 'btn btn-primary'

app/views/rental_orders/new.html.haml
- model_class = RentalOrder
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/rental_orders/show.html.haml
- model_class = RentalOrder
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:customer_id) + ':'
  %br
  = rental_order.customer.decorate.full_name
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = rental_order.user.email
%p
  %strong= model_class.human_attribute_name(:car_id) + ':'
  %br
  = rental_order.car.decorate.full_name
%p
  %strong= model_class.human_attribute_name(:start_date) + ':'
  %br
  = rental_order.start_date
%p
  %strong= model_class.human_attribute_name(:end_date) + ':'
  %br
  = rental_order.end_date
%p
  %strong= model_class.human_attribute_name(:rental_cost) + ':'
  %br
  = rental_order.decorate.rental_cost


= link_to t('.back', :default => t("helpers.links.back")), rental_orders_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_rental_order_path(rental_order), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), rental_order_path(rental_order), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'